language: node_js
node_js:
  - "stable"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools

script:
  - echo "Deploy!"


after_success:
  - firebase deploy --token=$FIREBASE_TOKEN
